# Generated by Django 5.2.14 on 2026-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(default='Россия', max_length=120)),
                ('activity_type', models.CharField(max_length=200)),
                ('activity_kind', models.CharField(max_length=32)),
                ('difficulty', models.CharField(max_length=20)),
                ('difficulty_score', models.PositiveSmallIntegerField(default=1)),
                ('difficulty_max', models.PositiveSmallIntegerField(default=5)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('backpack_weight_kg', models.PositiveIntegerField(default=0)),
                ('max_people', models.PositiveIntegerField(default=20)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('date_summary', models.CharField(max_length=255)),
                ('gallery_extra_count', models.PositiveIntegerField(default=0)),
                ('status_label', models.CharField(blank=True, max_length=80)),
                ('spots_left', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('tags_secondary', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('breadcrumbs', models.JSONField(default=list)),
                ('date_slots', models.JSONField(default=list)),
                ('badges', models.JSONField(blank=True, null=True)),
                ('program_by_day', models.JSONField(default=list)),
                ('included', models.JSONField(default=list)),
                ('not_included', models.JSONField(default=list)),
                ('packing_list', models.JSONField(default=list)),
                ('faq', models.JSONField(default=list)),
                ('instructors', models.JSONField(default=list)),
                ('season', models.JSONField(blank=True, default=list, null=True)),
                ('holiday', models.JSONField(blank=True, default=list, null=True)),
                ('duration_category', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
