# Generated by Django 5.2.14 on 2026-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['id'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='activity_kind',
            field=models.CharField(help_text='hike, kayak, horse, mountain', max_length=32, verbose_name='Вид активности (код)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='activity_type',
            field=models.CharField(max_length=200, verbose_name='Тип активности (текст)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='backpack_weight_kg',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес рюкзака, кг'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='badges',
            field=models.JSONField(blank=True, help_text='label, color', null=True, verbose_name='Бейджи'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='breadcrumbs',
            field=models.JSONField(default=list, help_text='label, href', verbose_name='Хлебные крошки'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(default='Россия', max_length=120, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(default='RUB', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_slots',
            field=models.JSONField(default=list, help_text='id, label, start, end', verbose_name='Слоты дат'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_summary',
            field=models.CharField(max_length=255, verbose_name='Даты (кратко для карточки)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(help_text='easy, medium, hard, very_hard', max_length=20, verbose_name='Сложность (код)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty_max',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Максимум шкалы сложности'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Оценка сложности'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='distance_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Дистанция, км'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_category',
            field=models.JSONField(blank=True, default=list, help_text='long, weekend, oneday', null=True, verbose_name='Категория длительности'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Длительность, дней'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='faq',
            field=models.JSONField(default=list, help_text='q, a', verbose_name='Вопросы и ответы'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='gallery_extra_count',
            field=models.PositiveIntegerField(default=0, help_text='Число для подписи +N фотографий в галерее', verbose_name='Счётчик «ещё N фото»'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='holiday',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Праздники'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.JSONField(default=list, help_text='Список URL', verbose_name='Ссылки на изображения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included',
            field=models.JSONField(default=list, verbose_name='Включено в стоимость'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='instructors',
            field=models.JSONField(default=list, help_text='id, name, avatarUrl', verbose_name='Инструкторы'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_people',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимум человек в группе'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='not_included',
            field=models.JSONField(default=list, verbose_name='Не включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='packing_list',
            field=models.JSONField(default=list, verbose_name='Список вещей'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='program_by_day',
            field=models.JSONField(default=list, help_text='day, title, body', verbose_name='Программа по дням'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='region',
            field=models.CharField(max_length=200, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=models.JSONField(blank=True, default=list, help_text='summer, winter, …', null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='spots_left',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось мест'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Метка статуса'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.JSONField(default=list, help_text='Список строк', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags_secondary',
            field=models.JSONField(default=list, verbose_name='Дополнительные теги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
    ]
