# Generated by Django 5.2.14 on 2026-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_verbose_names_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_slots',
            field=models.JSONField(default=list, help_text='Для календаря на сайте: id, label, start, end (даты ISO YYYY-MM-DD)', verbose_name='Слоты дат'),
        ),
    ]
