# Generated by Django 5.2.14 on 2026-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_date_slots_help_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='date_summary',
        ),
    ]
