# Generated by Django 5.2.14 on 2026-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_date_summary_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_slots',
            field=models.JSONField(default=list, help_text='id, label, start, end (ISO YYYY-MM-DD). Краткая строка дат на сайте берётся из первого слота с датами.', verbose_name='Слоты дат'),
        ),
    ]
