# Generated by Django 5.2 — только help_text у date_slots (без изменений Season).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0018_region_model_tour_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="date_slots",
            field=models.JSONField(
                default=list,
                help_text="Слоты: start и end (ISO YYYY-MM-DD). Подпись для сайта — при сохранении. Ключ слота в БД (d1, …) не хранится в JSON.",
                verbose_name="Слоты дат",
            ),
        ),
    ]
