"""Данные для python manage.py seed_tours (совместимо с фронтом)."""

from .models import picsum_url as pic


def _slots(*items):
    return [{"id": i[0], "label": i[1], "start": i[2], "end": i[3]} for i in items]


def _inst(iid, name, seed):
    return [{"id": iid, "name": name, "avatarUrl": pic(seed, 200, 200)}]


SEED_TOURS = [
    {
        "slug": "yastrebinoe",
        "title": "Ястребиное. Поход из Петербурга со скалолазанием и тарзанкой",
        "region": "Карелия и Ленобласть",
        "country": "Россия",
        "activity_type": "Пешие походы",
        "activity_kind": "hike",
        "difficulty": "medium",
        "difficulty_score": 3,
        "difficulty_max": 5,
        "distance_km": 25,
        "duration_days": 3,
        "backpack_weight_kg": 16,
        "max_people": 22,
        "price": 7900,
        "old_price": None,
        "currency": "RUB",
        "date_summary": "с 8 по 10 мая 2026 - 3 дня",
        "gallery_extra_count": 98,
        "status_label": "ЧЕРЕЗ 3 ЧАСА",
        "spots_left": None,
        "description": (
            "Трёхдневный поход с элементами скалолазания и тарзанки у озера. "
            "Подходит тем, кто хочет совместить активный отдых и красивые виды Ленобласти."
        ),
        "tags": ["Карелия и Ленобласть", "Россия", "Пешие походы", "На выходные"],
        "tags_secondary": ["Скалолазание", "С рюкзаками", "С палатками", "Автономные"],
        "images": [
            pic("turist-yastrebinoe-cover"),
            pic("turist-yastrebinoe-g2"),
            pic("turist-yastrebinoe-g3"),
            pic("turist-yastrebinoe-g4"),
        ],
        "breadcrumbs": [
            {"label": "Главная", "href": "/"},
            {"label": "Россия", "href": "/tours?region=Россия"},
            {"label": "Карелия и Ленобласть", "href": "/tours?region=Карелия%20и%20Ленобласть"},
        ],
        "date_slots": _slots(
            ("d1", "8 — 10 мая 2026", "2026-05-08", "2026-05-10"),
            ("d2", "15 — 17 мая 2026", "2026-05-15", "2026-05-17"),
        ),
        "badges": None,
        "program_by_day": [
            {"day": 1, "title": "Сбор и переход", "body": "Встреча в Санкт-Петербурге, трансфер к месту старта, установка лагеря, короткая разминка на скалах."},
            {"day": 2, "title": "Скалы и озеро", "body": "Маршрут вдоль берега, скалолазание с инструктором, свободное время и купание (по погоде)."},
            {"day": 3, "title": "Тарзанка и выход", "body": "Утренняя тарзанка, сбор палаток, возвращение в город."},
        ],
        "included": ["Инструктор", "Страховка на маршруте", "Групповое снаряжение"],
        "not_included": ["Питание", "Личное снаряжение", "Дорога до места встречи"],
        "packing_list": ["Рюкзак 40–60 л", "Спальник", "Коврик", "Термос", "Аптечка"],
        "faq": [{"q": "Нужен ли опыт?", "a": "Достаточно базовой физической формы; инструктор проведёт инструктаж."}],
        "instructors": _inst("i1", "Георгий Айвазошвили", "turist-yastrebinoe-instr-geo"),
        "season": ["spring", "summer"],
        "holiday": ["may"],
        "duration_category": ["weekend"],
    },
    {
        "slug": "ladoga-coast",
        "title": "Ладожский берег. Пеший поход с палатками из Санкт-Петербурга",
        "region": "Карелия и Ленобласть",
        "country": "Россия",
        "activity_type": "Пешие походы",
        "activity_kind": "hike",
        "difficulty": "medium",
        "difficulty_score": 3,
        "difficulty_max": 5,
        "distance_km": 25,
        "duration_days": 3,
        "backpack_weight_kg": 14,
        "max_people": 18,
        "price": 7900,
        "old_price": None,
        "currency": "RUB",
        "date_summary": "с 8 по 10 мая 2026 - 3 дня",
        "gallery_extra_count": 42,
        "status_label": "ЧЕРЕЗ 3 ЧАСА",
        "spots_left": None,
        "description": "Классический выходной поход вдоль Ладоги с ночёвками в палатках.",
        "tags": ["Карелия и Ленобласть", "Россия", "Пешие походы", "На выходные"],
        "tags_secondary": ["С палатками", "С рюкзаками"],
        "images": [pic("turist-ladoga-cover"), pic("turist-ladoga-g2")],
        "breadcrumbs": [
            {"label": "Главная", "href": "/"},
            {"label": "Россия", "href": "/tours?region=Россия"},
            {"label": "Карелия и Ленобласть", "href": "/tours?region=Карелия%20и%20Ленобласть"},
        ],
        "date_slots": _slots(("d1", "8 — 10 мая 2026", "2026-05-08", "2026-05-10")),
        "badges": None,
        "program_by_day": [
            {"day": 1, "title": "Старт", "body": "Выезд из Петербурга, первый лагерь."},
            {"day": 2, "title": "Берег", "body": "Переходы по берегу, виды на воду."},
            {"day": 3, "title": "Финиш", "body": "Выход к транспорту и возвращение."},
        ],
        "included": ["Инструктор", "Карта маршрута"],
        "not_included": ["Питание", "Палатка (можно арендовать)"],
        "packing_list": ["Палатка", "Спальник", "Посуда"],
        "faq": [],
        "instructors": _inst("i1", "Георгий Айвазошвили", "turist-ladoga-instr-geo"),
        "season": ["spring", "summer"],
        "holiday": [],
        "duration_category": ["weekend"],
    },
    {
        "slug": "dve-usadby",
        "title": "Две усадьбы. Однодневный треккинг в Подмосковье",
        "region": "Московская область",
        "country": "Россия",
        "activity_type": "Пешие походы",
        "activity_kind": "hike",
        "difficulty": "easy",
        "difficulty_score": 2,
        "difficulty_max": 5,
        "distance_km": 21,
        "duration_days": 1,
        "backpack_weight_kg": 8,
        "max_people": 25,
        "price": 3300,
        "old_price": None,
        "currency": "RUB",
        "date_summary": "8 мая 2026 - 1 день",
        "gallery_extra_count": 15,
        "status_label": "ЧЕРЕЗ 3 ЧАСА",
        "spots_left": None,
        "description": "Однодневный маршрут с посещением двух усадебных парков.",
        "tags": ["Московская область", "Россия", "Пешие походы", "Однодневные"],
        "tags_secondary": ["Треккинг", "История"],
        "images": [pic("turist-dve-usadby-cover"), pic("turist-dve-usadby-g2")],
        "breadcrumbs": [
            {"label": "Главная", "href": "/"},
            {"label": "Россия", "href": "/tours?region=Россия"},
            {"label": "Московская область", "href": "/tours?region=Московская%20область"},
        ],
        "date_slots": _slots(("d1", "8 мая 2026", "2026-05-08", "2026-05-08")),
        "badges": None,
        "program_by_day": [{"day": 1, "title": "Маршрут", "body": "Сбор в Москве, переходы, экскурсии."}],
        "included": ["Гид"],
        "not_included": ["Обед"],
        "packing_list": ["Удобная обувь", "Вода"],
        "faq": [],
        "instructors": _inst("i2", "Мария Соколова", "turist-dve-usadby-instr-maria"),
        "season": ["spring", "summer", "autumn"],
        "holiday": ["may"],
        "duration_category": ["oneday"],
    },
    {
        "slug": "elbrus-hotel",
        "title": "Восхождение на Эльбрус с проживанием в отеле",
        "region": "Кавказ",
        "country": "Россия",
        "activity_type": "Горные",
        "activity_kind": "mountain",
        "difficulty": "very_hard",
        "difficulty_score": 5,
        "difficulty_max": 5,
        "distance_km": 70,
        "duration_days": 9,
        "backpack_weight_kg": 20,
        "max_people": 12,
        "price": 79900,
        "old_price": 89900,
        "currency": "RUB",
        "date_summary": "с 9 по 17 мая 2026 - 9 дней",
        "gallery_extra_count": 120,
        "status_label": "ЧЕРЕЗ ДЕНЬ",
        "spots_left": 4,
        "description": "Программа восхождения с проживанием в отеле на этапах подготовки.",
        "tags": ["Кавказ", "Россия", "Горные", "Большие (от 5 дней)"],
        "tags_secondary": ["Акклиматизация", "С инструктором"],
        "images": [pic("turist-elbrus-cover"), pic("turist-elbrus-g2")],
        "breadcrumbs": [
            {"label": "Главная", "href": "/"},
            {"label": "Россия", "href": "/tours?region=Россия"},
            {"label": "Кавказ", "href": "/tours?region=Кавказ"},
        ],
        "date_slots": _slots(("d1", "9 — 17 мая 2026", "2026-05-09", "2026-05-17")),
        "badges": [{"label": "Осталось 4 места", "color": "yellow"}, {"label": "Ранние пташки", "color": "green"}],
        "program_by_day": [
            {"day": 1, "title": "Прилёт", "body": "Трансфер, размещение, инструктаж."},
            {"day": 2, "title": "Акклиматизация", "body": "Выходы на средние высоты."},
        ],
        "included": ["Инструкторы", "Проживание по программе", "Групповое снаряжение"],
        "not_included": ["Авиабилеты", "Страховка от несчастных случаев расширенная"],
        "packing_list": ["Высотное снаряжение по списку", "Мембранная одежда"],
        "faq": [{"q": "Нужна ли страховка?", "a": "Да, обязательна — поможем оформить."}],
        "instructors": _inst("i3", "Алексей Вершинин", "turist-elbrus-instr-alex"),
        "season": ["spring", "summer"],
        "holiday": [],
        "duration_category": ["long"],
    },
    {
        "slug": "kayak-onega",
        "title": "Сплав на каяках по Онежскому заливу",
        "region": "Карелия и Ленобласть",
        "country": "Россия",
        "activity_type": "Сплавы",
        "activity_kind": "kayak",
        "difficulty": "easy",
        "difficulty_score": 2,
        "difficulty_max": 5,
        "distance_km": 14,
        "duration_days": 2,
        "backpack_weight_kg": 10,
        "max_people": 14,
        "price": 5600,
        "old_price": None,
        "currency": "RUB",
        "date_summary": "с 12 по 13 мая 2026 - 2 дня",
        "gallery_extra_count": 30,
        "status_label": "",
        "spots_left": None,
        "description": "Спокойный водный маршрут для новичков.",
        "tags": ["Карелия и Ленобласть", "Россия", "Сплавы", "На выходные"],
        "tags_secondary": ["Каяки"],
        "images": [pic("turist-kayak-cover"), pic("turist-kayak-g2")],
        "breadcrumbs": [
            {"label": "Главная", "href": "/"},
            {"label": "Россия", "href": "/"},
            {"label": "Карелия и Ленобласть", "href": "/tours"},
        ],
        "date_slots": _slots(("d1", "12 — 13 мая 2026", "2026-05-12", "2026-05-13")),
        "badges": None,
        "program_by_day": [{"day": 1, "title": "Вода", "body": "Инструктаж и сплав."}],
        "included": ["Каяк", "Жилет"],
        "not_included": ["Питание"],
        "packing_list": ["Смена одежды", "Крем от солнца"],
        "faq": [],
        "instructors": _inst("i2", "Мария Соколова", "turist-kayak-instr-maria"),
        "season": ["summer"],
        "holiday": [],
        "duration_category": ["weekend"],
    },
    {
        "slug": "altai-tea",
        "title": "Алтай: горные тропы и чайные домики",
        "region": "Алтай",
        "country": "Россия",
        "activity_type": "Пешие походы",
        "activity_kind": "hike",
        "difficulty": "hard",
        "difficulty_score": 4,
        "difficulty_max": 5,
        "distance_km": 55,
        "duration_days": 7,
        "backpack_weight_kg": 18,
        "max_people": 16,
        "price": 45900,
        "old_price": None,
        "currency": "RUB",
        "date_summary": "с 1 по 7 июня 2026 - 7 дней",
        "gallery_extra_count": 64,
        "status_label": "",
        "spots_left": None,
        "description": "Недельный поход по знаковым местам Алтая.",
        "tags": ["Алтай", "Россия", "Пешие походы", "Большие (от 5 дней)"],
        "tags_secondary": ["Горы", "С рюкзаками"],
        "images": [pic("turist-altai-cover"), pic("turist-altai-g2")],
        "breadcrumbs": [
            {"label": "Главная", "href": "/"},
            {"label": "Россия", "href": "/"},
            {"label": "Алтай", "href": "/tours"},
        ],
        "date_slots": _slots(("d1", "1 — 7 июня 2026", "2026-06-01", "2026-06-07")),
        "badges": None,
        "program_by_day": [{"day": 1, "title": "Старт", "body": "Встреча группы."}],
        "included": ["Инструктор", "Питание по программе"],
        "not_included": ["Билеты до Горно-Алтайска"],
        "packing_list": ["Рюкзак", "Спальник"],
        "faq": [],
        "instructors": _inst("i3", "Алексей Вершинин", "turist-altai-instr-alex"),
        "season": ["summer"],
        "holiday": ["june"],
        "duration_category": ["long"],
    },
]
